#!/bin/bash

##
# Module aliases.
# Should be updated here when app or lib are added to the project.
##

# Apps
MODULE_ALIAS_APP_NX_NG_STARTER="app:nx-ng-starter"
MODULE_ALIAS_APP_API="app:api"
# Apps E2E
MODULE_ALIAS_APP_NX_NG_STARTER_E2E="app:nx-ng-starter-e2e"
# Libs
MODULE_ALIAS_LIB_API_INTERFACE="lib:api-interface"
MODULE_ALIAS_LIB_MOCKS_CORE="lib:mocks-core"
MODULE_ALIAS_LIB_SHARED_CORE="lib:shared-core"
MODULE_ALIAS_LIB_PROTO="lib:proto"

reportSupportedModuleAliases() {
  TITLE="<< MODULE ALIASES >>"
  NX_NG_STARTER="MODULE_ALIAS_APP_NX_NG_STARTER: $MODULE_ALIAS_APP_NX_NG_STARTER"
  API="MODULE_ALIAS_APP_API: $MODULE_ALIAS_APP_API"

  NX_NG_STARTER_E2E="MODULE_ALIAS_APP_NX_NG_STARTER_E2E: $MODULE_ALIAS_APP_NX_NG_STARTER_E2E"

  API_INTERFACE="MODULE_ALIAS_LIB_API_INTERFACE: $MODULE_ALIAS_LIB_API_INTERFACE"
  SHARED_CORE="MODULE_ALIAS_LIB_SHARED_CORE: $MODULE_ALIAS_LIB_SHARED_CORE"
  MOCKS_CORE="MODULE_ALIAS_LIB_MOCKS_CORE: $MODULE_ALIAS_LIB_MOCKS_CORE"
  NOTIFICATIONS_CORE="MODULE_ALIAS_LIB_NOTIFICATIONS_CORE: $MODULE_ALIAS_LIB_NOTIFICATIONS_CORE"
  YAMAPS_CORE="MODULE_ALIAS_LIB_YAMAPS_CORE: $MODULE_ALIAS_LIB_YAMAPS_CORE"
  PROTO="MODULE_ALIAS_LIB_PROTO: $MODULE_ALIAS_LIB_PROTO"
  printf "${LIGHT_BLUE}<< %s >>${DEFAULT}\n
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${YELLOW} %s
    ${WHITE} %s\n\n" "$TITLE" "$NX_NG_STARTER" "$API" "$NX_NG_STARTER_E2E" "$API_INTERFACE" "$SHARED_CORE" "$MOCKS_CORE" "$NOTIFICATIONS_CORE" "$YAMAPS_CORE" "$PROTO"
}

##
# Supported module (apps and libs) aliases.
##
if [ "$1" = "?" ]; then
  reportSupportedModuleAliases
fi
