module.exports = {
  projects: [
    '<rootDir>/apps/api',
    '<rootDir>/apps/client',
    '<rootDir>/apps/documentation',
    '<rootDir>/apps/elements',
    '<rootDir>/apps/elements-testing',
    '<rootDir>/libs/api-interface',
    '<rootDir>/libs/client-chatbot',
    '<rootDir>/libs/client-components',
    '<rootDir>/libs/client-core',
    '<rootDir>/libs/client-gql',
    '<rootDir>/libs/client-material',
    '<rootDir>/libs/client-services',
    '<rootDir>/libs/client-sidebar',
    '<rootDir>/libs/client-store',
    '<rootDir>/libs/client-translate',
    '<rootDir>/libs/client-util',
    '<rootDir>/libs/client-unit-testing',
    '<rootDir>/libs/proto',
  ],
};
