// source: common.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var google_protobuf_any_pb = require('google-protobuf/google/protobuf/any_pb.js');
goog.object.extend(proto, google_protobuf_any_pb);
goog.exportSymbol('proto.nxngstarter.CommonEntities', null, global);
goog.exportSymbol('proto.nxngstarter.CommonEntity', null, global);
goog.exportSymbol('proto.nxngstarter.CommonEntityFilterDto', null, global);
goog.exportSymbol('proto.nxngstarter.SampleServiceRequest', null, global);
goog.exportSymbol('proto.nxngstarter.SampleServiceResponse', null, global);
goog.exportSymbol('proto.nxngstarter.SampleServiceResponse.ResponseData', null, global);
goog.exportSymbol('proto.nxngstarter.SubEntity', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.CommonEntities = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nxngstarter.CommonEntities.repeatedFields_, null);
};
goog.inherits(proto.nxngstarter.CommonEntities, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.CommonEntities.displayName = 'proto.nxngstarter.CommonEntities';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.CommonEntity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.nxngstarter.CommonEntity.repeatedFields_, null);
};
goog.inherits(proto.nxngstarter.CommonEntity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.CommonEntity.displayName = 'proto.nxngstarter.CommonEntity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.SubEntity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nxngstarter.SubEntity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.SubEntity.displayName = 'proto.nxngstarter.SubEntity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.CommonEntityFilterDto = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nxngstarter.CommonEntityFilterDto, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.CommonEntityFilterDto.displayName = 'proto.nxngstarter.CommonEntityFilterDto';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.SampleServiceRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nxngstarter.SampleServiceRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.SampleServiceRequest.displayName = 'proto.nxngstarter.SampleServiceRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.SampleServiceResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nxngstarter.SampleServiceResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.SampleServiceResponse.displayName = 'proto.nxngstarter.SampleServiceResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.nxngstarter.SampleServiceResponse.ResponseData = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.nxngstarter.SampleServiceResponse.ResponseData, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.nxngstarter.SampleServiceResponse.ResponseData.displayName = 'proto.nxngstarter.SampleServiceResponse.ResponseData';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nxngstarter.CommonEntities.repeatedFields_ = [2];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.CommonEntities.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.CommonEntities.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.CommonEntities} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntities.toObject = function(includeInstance, msg) {
  var f, obj = {
    count: jspb.Message.getFieldWithDefault(msg, 1, 0),
    entitiesList: jspb.Message.toObjectList(msg.getEntitiesList(),
    proto.nxngstarter.CommonEntity.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.CommonEntities}
 */
proto.nxngstarter.CommonEntities.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.CommonEntities;
  return proto.nxngstarter.CommonEntities.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.CommonEntities} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.CommonEntities}
 */
proto.nxngstarter.CommonEntities.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCount(value);
      break;
    case 2:
      var value = new proto.nxngstarter.CommonEntity;
      reader.readMessage(value,proto.nxngstarter.CommonEntity.deserializeBinaryFromReader);
      msg.addEntities(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.CommonEntities.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.CommonEntities.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.CommonEntities} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntities.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getCount();
  if (f !== 0) {
    writer.writeInt64(
      1,
      f
    );
  }
  f = message.getEntitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.nxngstarter.CommonEntity.serializeBinaryToWriter
    );
  }
};


/**
 * optional int64 count = 1;
 * @return {number}
 */
proto.nxngstarter.CommonEntities.prototype.getCount = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.CommonEntities} returns this
 */
proto.nxngstarter.CommonEntities.prototype.setCount = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};


/**
 * repeated CommonEntity entities = 2;
 * @return {!Array<!proto.nxngstarter.CommonEntity>}
 */
proto.nxngstarter.CommonEntities.prototype.getEntitiesList = function() {
  return /** @type{!Array<!proto.nxngstarter.CommonEntity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nxngstarter.CommonEntity, 2));
};


/**
 * @param {!Array<!proto.nxngstarter.CommonEntity>} value
 * @return {!proto.nxngstarter.CommonEntities} returns this
*/
proto.nxngstarter.CommonEntities.prototype.setEntitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.nxngstarter.CommonEntity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nxngstarter.CommonEntity}
 */
proto.nxngstarter.CommonEntities.prototype.addEntities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.nxngstarter.CommonEntity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nxngstarter.CommonEntities} returns this
 */
proto.nxngstarter.CommonEntities.prototype.clearEntitiesList = function() {
  return this.setEntitiesList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.nxngstarter.CommonEntity.repeatedFields_ = [6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.CommonEntity.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.CommonEntity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.CommonEntity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntity.toObject = function(includeInstance, msg) {
  var f, obj = {
    string1: jspb.Message.getFieldWithDefault(msg, 1, ""),
    num1: jspb.Message.getFieldWithDefault(msg, 2, 0),
    num2: jspb.Message.getFieldWithDefault(msg, 3, 0),
    boolean1: jspb.Message.getBooleanFieldWithDefault(msg, 4, false),
    float1: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    any1: (f = msg.getAny1()) && google_protobuf_any_pb.Any.toObject(includeInstance, f),
    subentitiesarrayList: jspb.Message.toObjectList(msg.getSubentitiesarrayList(),
    proto.nxngstarter.SubEntity.toObject, includeInstance),
    subentittobj: (f = msg.getSubentittobj()) && proto.nxngstarter.SubEntity.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.CommonEntity}
 */
proto.nxngstarter.CommonEntity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.CommonEntity;
  return proto.nxngstarter.CommonEntity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.CommonEntity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.CommonEntity}
 */
proto.nxngstarter.CommonEntity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setString1(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNum1(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setNum2(value);
      break;
    case 4:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setBoolean1(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setFloat1(value);
      break;
    case 8:
      var value = new google_protobuf_any_pb.Any;
      reader.readMessage(value,google_protobuf_any_pb.Any.deserializeBinaryFromReader);
      msg.setAny1(value);
      break;
    case 6:
      var value = new proto.nxngstarter.SubEntity;
      reader.readMessage(value,proto.nxngstarter.SubEntity.deserializeBinaryFromReader);
      msg.addSubentitiesarray(value);
      break;
    case 7:
      var value = new proto.nxngstarter.SubEntity;
      reader.readMessage(value,proto.nxngstarter.SubEntity.deserializeBinaryFromReader);
      msg.setSubentittobj(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.CommonEntity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.CommonEntity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.CommonEntity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getString1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getNum1();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getNum2();
  if (f !== 0) {
    writer.writeInt64(
      3,
      f
    );
  }
  f = message.getBoolean1();
  if (f) {
    writer.writeBool(
      4,
      f
    );
  }
  f = message.getFloat1();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getAny1();
  if (f != null) {
    writer.writeMessage(
      8,
      f,
      google_protobuf_any_pb.Any.serializeBinaryToWriter
    );
  }
  f = message.getSubentitiesarrayList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.nxngstarter.SubEntity.serializeBinaryToWriter
    );
  }
  f = message.getSubentittobj();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      proto.nxngstarter.SubEntity.serializeBinaryToWriter
    );
  }
};


/**
 * optional string string1 = 1;
 * @return {string}
 */
proto.nxngstarter.CommonEntity.prototype.getString1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.setString1 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 num1 = 2;
 * @return {number}
 */
proto.nxngstarter.CommonEntity.prototype.getNum1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.setNum1 = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int64 num2 = 3;
 * @return {number}
 */
proto.nxngstarter.CommonEntity.prototype.getNum2 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.setNum2 = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional bool boolean1 = 4;
 * @return {boolean}
 */
proto.nxngstarter.CommonEntity.prototype.getBoolean1 = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 4, false));
};


/**
 * @param {boolean} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.setBoolean1 = function(value) {
  return jspb.Message.setProto3BooleanField(this, 4, value);
};


/**
 * optional float float1 = 5;
 * @return {number}
 */
proto.nxngstarter.CommonEntity.prototype.getFloat1 = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.setFloat1 = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional google.protobuf.Any any1 = 8;
 * @return {?proto.google.protobuf.Any}
 */
proto.nxngstarter.CommonEntity.prototype.getAny1 = function() {
  return /** @type{?proto.google.protobuf.Any} */ (
    jspb.Message.getWrapperField(this, google_protobuf_any_pb.Any, 8));
};


/**
 * @param {?proto.google.protobuf.Any|undefined} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
*/
proto.nxngstarter.CommonEntity.prototype.setAny1 = function(value) {
  return jspb.Message.setWrapperField(this, 8, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.clearAny1 = function() {
  return this.setAny1(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nxngstarter.CommonEntity.prototype.hasAny1 = function() {
  return jspb.Message.getField(this, 8) != null;
};


/**
 * repeated SubEntity subEntitiesArray = 6;
 * @return {!Array<!proto.nxngstarter.SubEntity>}
 */
proto.nxngstarter.CommonEntity.prototype.getSubentitiesarrayList = function() {
  return /** @type{!Array<!proto.nxngstarter.SubEntity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.nxngstarter.SubEntity, 6));
};


/**
 * @param {!Array<!proto.nxngstarter.SubEntity>} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
*/
proto.nxngstarter.CommonEntity.prototype.setSubentitiesarrayList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.nxngstarter.SubEntity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.nxngstarter.SubEntity}
 */
proto.nxngstarter.CommonEntity.prototype.addSubentitiesarray = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.nxngstarter.SubEntity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.clearSubentitiesarrayList = function() {
  return this.setSubentitiesarrayList([]);
};


/**
 * optional SubEntity subEntittObj = 7;
 * @return {?proto.nxngstarter.SubEntity}
 */
proto.nxngstarter.CommonEntity.prototype.getSubentittobj = function() {
  return /** @type{?proto.nxngstarter.SubEntity} */ (
    jspb.Message.getWrapperField(this, proto.nxngstarter.SubEntity, 7));
};


/**
 * @param {?proto.nxngstarter.SubEntity|undefined} value
 * @return {!proto.nxngstarter.CommonEntity} returns this
*/
proto.nxngstarter.CommonEntity.prototype.setSubentittobj = function(value) {
  return jspb.Message.setWrapperField(this, 7, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nxngstarter.CommonEntity} returns this
 */
proto.nxngstarter.CommonEntity.prototype.clearSubentittobj = function() {
  return this.setSubentittobj(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nxngstarter.CommonEntity.prototype.hasSubentittobj = function() {
  return jspb.Message.getField(this, 7) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.SubEntity.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.SubEntity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.SubEntity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SubEntity.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.SubEntity}
 */
proto.nxngstarter.SubEntity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.SubEntity;
  return proto.nxngstarter.SubEntity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.SubEntity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.SubEntity}
 */
proto.nxngstarter.SubEntity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.SubEntity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.SubEntity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.SubEntity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SubEntity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.nxngstarter.SubEntity.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.SubEntity} returns this
 */
proto.nxngstarter.SubEntity.prototype.setId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.CommonEntityFilterDto.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.CommonEntityFilterDto.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.CommonEntityFilterDto} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntityFilterDto.toObject = function(includeInstance, msg) {
  var f, obj = {
    num1: jspb.Message.getFieldWithDefault(msg, 1, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.CommonEntityFilterDto}
 */
proto.nxngstarter.CommonEntityFilterDto.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.CommonEntityFilterDto;
  return proto.nxngstarter.CommonEntityFilterDto.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.CommonEntityFilterDto} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.CommonEntityFilterDto}
 */
proto.nxngstarter.CommonEntityFilterDto.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setNum1(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.CommonEntityFilterDto.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.CommonEntityFilterDto.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.CommonEntityFilterDto} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.CommonEntityFilterDto.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getNum1();
  if (f !== 0) {
    writer.writeInt32(
      1,
      f
    );
  }
};


/**
 * optional int32 num1 = 1;
 * @return {number}
 */
proto.nxngstarter.CommonEntityFilterDto.prototype.getNum1 = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.CommonEntityFilterDto} returns this
 */
proto.nxngstarter.CommonEntityFilterDto.prototype.setNum1 = function(value) {
  return jspb.Message.setProto3IntField(this, 1, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.SampleServiceRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.SampleServiceRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.SampleServiceRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    input1: jspb.Message.getFieldWithDefault(msg, 1, ""),
    input2: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.SampleServiceRequest}
 */
proto.nxngstarter.SampleServiceRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.SampleServiceRequest;
  return proto.nxngstarter.SampleServiceRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.SampleServiceRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.SampleServiceRequest}
 */
proto.nxngstarter.SampleServiceRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput1(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setInput2(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.SampleServiceRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.SampleServiceRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.SampleServiceRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getInput1();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getInput2();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string input1 = 1;
 * @return {string}
 */
proto.nxngstarter.SampleServiceRequest.prototype.getInput1 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.SampleServiceRequest} returns this
 */
proto.nxngstarter.SampleServiceRequest.prototype.setInput1 = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string input2 = 2;
 * @return {string}
 */
proto.nxngstarter.SampleServiceRequest.prototype.getInput2 = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.SampleServiceRequest} returns this
 */
proto.nxngstarter.SampleServiceRequest.prototype.setInput2 = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.SampleServiceResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.SampleServiceResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.SampleServiceResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    status: jspb.Message.getFieldWithDefault(msg, 1, ""),
    data: (f = msg.getData()) && proto.nxngstarter.SampleServiceResponse.ResponseData.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.SampleServiceResponse}
 */
proto.nxngstarter.SampleServiceResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.SampleServiceResponse;
  return proto.nxngstarter.SampleServiceResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.SampleServiceResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.SampleServiceResponse}
 */
proto.nxngstarter.SampleServiceResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStatus(value);
      break;
    case 2:
      var value = new proto.nxngstarter.SampleServiceResponse.ResponseData;
      reader.readMessage(value,proto.nxngstarter.SampleServiceResponse.ResponseData.deserializeBinaryFromReader);
      msg.setData(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.SampleServiceResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.SampleServiceResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.SampleServiceResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStatus();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getData();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.nxngstarter.SampleServiceResponse.ResponseData.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.toObject = function(opt_includeInstance) {
  return proto.nxngstarter.SampleServiceResponse.ResponseData.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.nxngstarter.SampleServiceResponse.ResponseData} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.toObject = function(includeInstance, msg) {
  var f, obj = {
    stringvalue: jspb.Message.getFieldWithDefault(msg, 1, ""),
    intvalue: jspb.Message.getFieldWithDefault(msg, 3, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.nxngstarter.SampleServiceResponse.ResponseData}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.nxngstarter.SampleServiceResponse.ResponseData;
  return proto.nxngstarter.SampleServiceResponse.ResponseData.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.nxngstarter.SampleServiceResponse.ResponseData} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.nxngstarter.SampleServiceResponse.ResponseData}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setStringvalue(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntvalue(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.nxngstarter.SampleServiceResponse.ResponseData.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.nxngstarter.SampleServiceResponse.ResponseData} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getStringvalue();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIntvalue();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
};


/**
 * optional string stringValue = 1;
 * @return {string}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.getStringvalue = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.SampleServiceResponse.ResponseData} returns this
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.setStringvalue = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 intValue = 3;
 * @return {number}
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.getIntvalue = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.nxngstarter.SampleServiceResponse.ResponseData} returns this
 */
proto.nxngstarter.SampleServiceResponse.ResponseData.prototype.setIntvalue = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional string status = 1;
 * @return {string}
 */
proto.nxngstarter.SampleServiceResponse.prototype.getStatus = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.nxngstarter.SampleServiceResponse} returns this
 */
proto.nxngstarter.SampleServiceResponse.prototype.setStatus = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional ResponseData data = 2;
 * @return {?proto.nxngstarter.SampleServiceResponse.ResponseData}
 */
proto.nxngstarter.SampleServiceResponse.prototype.getData = function() {
  return /** @type{?proto.nxngstarter.SampleServiceResponse.ResponseData} */ (
    jspb.Message.getWrapperField(this, proto.nxngstarter.SampleServiceResponse.ResponseData, 2));
};


/**
 * @param {?proto.nxngstarter.SampleServiceResponse.ResponseData|undefined} value
 * @return {!proto.nxngstarter.SampleServiceResponse} returns this
*/
proto.nxngstarter.SampleServiceResponse.prototype.setData = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.nxngstarter.SampleServiceResponse} returns this
 */
proto.nxngstarter.SampleServiceResponse.prototype.clearData = function() {
  return this.setData(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.nxngstarter.SampleServiceResponse.prototype.hasData = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto.nxngstarter);
