# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# uses: rfprod/nx-ng-starter/.github/actions/setup-environment@main
# or
# uses: ./.github/actions/setup-environment

name: setup-environment
description: Set up the environment. This composite action should be used in two workflows - pr-validation and trunk-on-push.

inputs:
  compodoc:
    description: Install compodoc as a global npm package to build documentation
    required: true
    default: 'false'
  cypress:
    description: Install cypress to run e2e tests
    required: true
    default: 'false'
  firebase-tools:
    description: Install firebase-tools as a global npm package to deploy to firebase
    required: true
    default: 'false'
  node-version:
    description: NodeJS version
    required: true
    default: 16.x

runs:
  using: 'composite'
  steps:
    - name: Disable session history
      uses: ./.github/actions/disable-session-history

    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        check-latest: true

    - name: Configure kernel
      uses: ./.github/actions/configure-kernel

    - name: Use yarn v1 required for integrity check
      uses: ./.github/actions/use-yarn-v1

    - name: Workspace cache
      id: workspace-cache
      uses: ./.github/actions/workspace-cache
      with:
        node-version: ${{ inputs.node-version }}

    - name: Workspace integrity check
      if: steps.workspace-cache.outputs.cache-hit == 'true'
      shell: bash
      run: yarn workspace:integrity-check

    - name: Install project dependencies
      shell: bash
      run: yarn install:ci

    - name: Install global compodoc
      if: inputs.compodoc == 'true'
      shell: bash
      run: npm i -g @compodoc/compodoc

    - name: Install cypress
      if: inputs.cypress == 'true'
      shell: bash
      run: npx cypress install

    - name: Install firebase-tools
      if: inputs.firebase-tools == 'true'
      shell: bash
      run: npm i -g firebase-tools

    - name: Install secure depete
      shell: bash
      run: |
        sudo apt update
        sudo apt install secure-delete
