name: Bug Report
description: Create a bug report to help us improve
title: '[Bug]: '
labels: ['Bug']
assignees:
  - rfprod
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If you want us to be able to get in touch with you directly via email if we need more info, please specify your email.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: How to reproduce?
      description: A list of steps to reproduce the unwanted behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: What did you expect?
      description: Describe the expected behavior
      placeholder: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: device-specification-and-environment
    attributes:
      label: Device specification and environment
      description: |
        Filling in the device specification and environment helps address the issue faster.
        - type: device type [e.g. desktop, laptop, tablet, smartphone]
        - OS: operating system [e.g. Ubuntu 20.04, Windows 10, Android 12, iOS 8.1]
        - Node: nodejs version [e.g. 13.14.0, 16.6.0, N/A]
        - npm: npm version [e.g. 13.14.0, 16.6.0, N/A]
        - yarn: yarn version [e.g. 1.22.17, 1.22.19, N/A]
        Examples:
          - **type**: desktop
          - **OS**: Ubuntu 20.04
          - **Node**: 13.14.0
          - **npm**: 7.6.3
          - **yarn**: 1.22.19
      value: |
        - type:
        - OS:
        - Node:
        - npm:
        - yarn:
      render: Markdown
    validations:
      required: false
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - N/A
        - Firefox
        - Chrome
        - Chromium
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rfprod/nx-ng-starter/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
