name: Feature Request
description: Suggest an idea for this project
title: '[Feature]: '
labels: ['Feature']
assignees:
  - rfprod
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: If you want us to be able to get in touch with you directly via email if we need more info, please specify your email.
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: problem-description
    attributes:
      label: Problem description
      description: Is your feature request relateed to a specific problem? Please describe.
      placeholder: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: preferred-solution
    attributes:
      label: Preferred solution description
      description: Describe the solution you'd like.
      placeholder: A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: alternative-solutions
    attributes:
      label: Alternative solutions description
      description: Describe alternatives you've considered.
      placeholder: A clear and concise description of any alternative solutions or features you've considered.
    validations:
      required: false
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the feature you are requesting!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/rfprod/nx-ng-starter/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
