# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# uses: rfprod/nx-ng-starter/.github/actions/disable-session-history@main
# or
# uses: ./.github/actions/disable-session-history

name: disable-session-history
description: Disable session history.

runs:
  using: 'composite'
  steps:
    - name: Don't save Bash session history
      shell: bash
      run: unset HISTFILE
