# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# uses: rfprod/nx-ng-starter/.github/actions/npm-publish@main
# or
# uses: ./.github/actions/npm-publish

name: npm-publish
description: Publish a library to NPM. This composite action should be only used in workflows that publish specific libraries to npm.

inputs:
  library-name:
    description: Name of the library to publish
    required: true
  npm-automation-token:
    description: NPM automation token for packages publishing
    required: true

runs:
  using: 'composite'
  steps:
    - name: Build ${{ inputs.library-name }}
      shell: bash
      run: npx nx build ${{ inputs.library-name }}

    - name: Publish the package to npmjs.org
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-automation-token }}" > ~/.npmrc
        cd ./dist/libs/${{ inputs.library-name }}
        npm publish --access public
        find ~/.npmrc -exec shred -fuz {} +
