# For more information see:
# - https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
# - https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions#outputsoutput_id

# The action can be referenced in workflows like:
# uses: rfprod/nx-ng-starter/.github/actions/npm-publish@main
# or
# uses: ./.github/actions/npm-publish

name: npm-publish
description: Publish a library to NPM. This composite action should be only used in workflows that publish specific libraries to npm.

inputs:
  library-name:
    description: Name of the library to publish
    required: true
  npm-automation-token:
    description: NPM automation token for package publishing
    required: false
    default: ''
  use-trusted-publishing:
    description: Use Trusted Publishing flow instead of NPM automation token
    required: false
    default: 'false'
  dry-run:
    description: Used by premerge workflow to confirm the ability to publish packages without doing so
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Build ${{ inputs.library-name }}
      shell: bash
      run: npx nx build ${{ inputs.library-name }}

    - name: Bail out on invalid inputs
      if: ${{ inputs.npm-automation-token == '' && inputs.use-trusted-publishing == 'false' }}
      shell: bash
      run: |
        MESSAGE=":x: Neither NPM automation token nor Trusted Publishing was configured for authentication."
        echo "${MESSAGE}"
        echo "### :package: Package publishing: ${LIBRARY_NAME}" >> $GITHUB_STEP_SUMMARY
        echo "${MESSAGE}" >> $GITHUB_STEP_SUMMARY
        exit 1
      env:
        LIBRARY_NAME: ${{ inputs.library-name }}

    - name: Verify the package is publishable
      id: verify
      shell: bash
      run: |
        set -euo pipefail

        PACKAGE_NAME="$(node -p "require('./package.json').name")"
        PACKAGE_VERSION="$(node -p "require('./package.json').version")"

        echo -e "package.json > name:\t$PACKAGE_NAME"
        echo -e "package.json > version:\t$PACKAGE_VERSION"

        [[ -z "$PACKAGE_NAME" || -z "$PACKAGE_VERSION" ]] && {
          echo "Package name or version missing" >&2; exit 1;
        }

        NPM_VIEW_STATUS=0
        NPM_VIEW_OUTPUT=$(npm view "$PACKAGE_NAME@$PACKAGE_VERSION" version 2>&1) || NPM_VIEW_STATUS=$?

        EXISTS=""
        if [ $NPM_VIEW_STATUS -eq 0 ]; then
          EXISTS="true"
          echo "npm view succeeded → the version exists"
        else
          echo "npm view failed → distinguish 404 from other errors"
          if echo "$NPM_VIEW_OUTPUT" | grep -qE '^npm ERR! code E404'; then
            EXISTS="false"
            echo "Package $PACKAGE_NAME@$PACKAGE_VERSION not found → will be published."
          else
            echo "Unexpected error while checking npm registry:" >&2
            echo "$NPM_VIEW_OUTPUT" >&2
            exit 1
          fi
        fi

        echo "name=$PACKAGE_NAME" >> $GITHUB_OUTPUT
        echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
        echo "exists=$EXISTS" >> $GITHUB_OUTPUT

    - name: Print summary
      shell: bash
      run: |
        PUBLISHING_METHOD=":ticket: Publish using NPM automation token."
        if [ "$USE_TRUSTED_PUBLISHING" == "true" ]; then PUBLISHING_METHOD=":ticket: Publish using Trusted Publishing."; fi
        echo "### :package: Package publishing: ${LIBRARY_NAME}" >> $GITHUB_STEP_SUMMARY
        echo "$PUBLISHING_METHOD" >> $GITHUB_STEP_SUMMARY
        echo "Package name: $PACKAGE_NAME" >> $GITHUB_STEP_SUMMARY
        echo "Package version: $PACKAGE_VERSION" >> $GITHUB_STEP_SUMMARY
        echo "Package exists on npmjs.org: $PACKAGE_EXISTS" >> $GITHUB_STEP_SUMMARY
        if [ "$PACKAGE_EXISTS" == "true" ]; then
          echo ":exclamation: $PACKAGE_NAME@$PACKAGE_VERSION already exists on npmjs.org." >> $GITHUB_STEP_SUMMARY
        fi
      env:
        LIBRARY_NAME: ${{ inputs.library-name }}
        USE_TRUSTED_PUBLISHING: ${{ inputs.use-trusted-publishing }}
        PACKAGE_NAME: ${{ steps.verify.outputs.name }}
        PACKAGE_VERSION: ${{ steps.verify.outputs.version }}
        PACKAGE_EXISTS: ${{ steps.verify.outputs.exists }}

    - name: Publish using a token
      if: ${{ steps.verify.outputs.exists == 'false' && inputs.npm-automation-token != '' && inputs.use-trusted-publishing == 'false' }}
      shell: bash
      run: |
        set -euo pipefail
        echo "//registry.npmjs.org/:_authToken=${NPM_AUTOMATION_TOKEN}" > ~/.npmrc
        cd ./dist/libs/"$LIBRARY_NAME"
        if [[ "$DRY_RUN" == "true" ]]; then
          npm publish --dry-run
        else
          npm publish --access public
        fi
        find ~/.npmrc -exec shred -fuz {} +
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        LIBRARY_NAME: ${{ inputs.library-name }}
        NPM_AUTOMATION_TOKEN: ${{ inputs.npm-automation-token }}

    - name: Publish using Trusted Publishing
      if: ${{ steps.verify.outputs.exists == 'false' && inputs.use-trusted-publishing == 'true' }}
      shell: bash
      run: |
        set -euo pipefail
        echo "registry=https://registry.npmjs.org/" > ~/.npmrc
        cd ./dist/libs/"$LIBRARY_NAME"
        if [[ "$DRY_RUN" == "true" ]]; then
          npm publish --dry-run
        else
          npm publish --access public
        fi
        find ~/.npmrc -exec shred -fuz {} +
      env:
        DRY_RUN: ${{ inputs.dry-run }}
        LIBRARY_NAME: ${{ inputs.library-name }}
        NPM_CONFIG_PROVENANCE: true
