# For more information see:
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows
# - https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations

# Note:
# This workflow might be used after code is merged into the master branch.
# The workflow is referenced in other workflows like:
# - nx-ns-starter/.github/actions/get-variables
# ./.github/actions/get-variables

name: get-variables
description: 'Get variables'
outputs:
  shortref:
    description: 'Branch name'
    value: ${{ steps.get-variables.outputs.shortref }}
  commitsha:
    description: 'GitHub commit SHA'
    value: ${{ steps.get-variables.outputs.commitsha }}
  yarncachedir:
    description: 'Yarn cache directory'
    value: ${{ steps.get-variables.outputs.yarncachedir }}

runs:
  using: 'composite'
  steps:
    - name: Get variables (branch name, commit hash, yarn cache directory)
      id: get-variables
      shell: bash
      run: |
        echo "::set-output name=shortref::${GITHUB_REF#refs/*/}";
        echo "::set-output name=commitsha::$(echo ${GITHUB_SHA})";
        echo "::set-output name=yarncachedir::$(yarn cache dir)";
