#!/bin/sh

# shellcheck source=.husky/_/husky.sh
. "$(dirname "$0")/_/husky.sh"

STAGED_FILES="$(git diff --cached --name-only --diff-filter=ACM | grep ".\(ts\|js\|html\|scss\)\{0,1\}$" || true)"

yarn lint:changed:fix || exit 1

printf '%s\n' "$STAGED_FILES" | while IFS= read -r FILE; do
  if [ "$FILE" != "" ]; then
    git add "$FILE"
  fi
done

npx nx affected --target tsc-check || exit 1
