name: codeowners-validator

on:
  schedule:
    - cron: '0 0 * * 0'

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.codeowners-validator
  cancel-in-progress: true

jobs:
  codeowners:
    runs-on: ubuntu-latest

    outputs:
      matrix: ${{ steps.get-codeowners.outputs.matrix }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          node-version: 16.x

      - name: Get codeowners
        id: get-codeowners
        run: npx nx run tools:get-codeowners

  validate:
    needs: codeowners
    runs-on: ubuntu-latest

    strategy:
      matrix:
        name: ${{ fromJSON(needs.codeowners.outputs.matrix) }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Validate a codeowner
        uses: ./.github/actions/validate-codeowner
        with:
          name: ${{ matrix.name }}
