# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: deploy-apps

on:
  workflow_call:
    inputs:
      api:
        type: boolean
        required: true
        default: false
      client:
        type: boolean
        required: true
        default: false
      elements:
        type: boolean
        required: true
        default: false
      documentation:
        type: boolean
        required: true
        default: false
    secrets:
      FIREBASE_DEPLOY_TOKEN:
        required: true

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.deploy-apps
  cancel-in-progress: true

jobs:
  checks:
    runs-on: ubuntu-latest

    outputs:
      api: ${{ steps.dist-exists.outputs.api }}
      client: ${{ steps.dist-exists.outputs.client }}
      elements: ${{ steps.dist-exists.outputs.elements }}
      documentation: ${{ steps.dist-exists.outputs.documentation }}

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Download dist artifact
        uses: ./.github/actions/dist-artifact-download

      - name: Check dists existence
        id: dist-exists
        shell: bash
        run: |
          echo "--"
          echo "-- Check api dist --"
          echo "--"
          API_DIST_DIR=./dist/apps/api
          API_DIST_EXISTS=false
          [ -d "$API_DIST_DIR" ] && API_DIST_EXISTS=true
          echo "api=$API_DIST_EXISTS" >> $GITHUB_OUTPUT
          echo "--"
          echo "-- Check client dist --"
          echo "--"
          CLIENT_DIST_DIR=./dist/apps/client
          CLIENT_DIST_EXISTS=false
          [ -d "$CLIENT_DIST_DIR" ] && CLIENT_DIST_EXISTS=true
          echo "client=$CLIENT_DIST_EXISTS" >> $GITHUB_OUTPUT
          echo "--"
          echo "-- Check elements dist --"
          echo "--"
          ELEMENTS_DIST_DIR=./dist/apps/api
          ELEMENTS_DIST_EXISTS=false
          [ -d "$ELEMENTS_DIST_DIR" ] && ELEMENTS_DIST_EXISTS=true
          echo "elements=$ELEMENTS_DIST_EXISTS" >> $GITHUB_OUTPUT
          echo "--"
          echo "-- Check documentation dist --"
          echo "--"
          DOCUMENTATION_DIST_DIR=./dist/apps/api
          DOCUMENTATION_DIST_EXISTS=false
          [ -d "$DOCUMENTATION_DIST_DIR" ] && DOCUMENTATION_DIST_EXISTS=true
          echo "documentation=$DOCUMENTATION_DIST_EXISTS" >> $GITHUB_OUTPUT

      - name: Print changes
        shell: bash
        run: |
          echo "### :rocket: Existing dists" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- API: $API" >> $GITHUB_STEP_SUMMARY
          echo "- CLIENT: $CLIENT" >> $GITHUB_STEP_SUMMARY
          echo "- ELEMENTS: $ELEMENTS" >> $GITHUB_STEP_SUMMARY
          echo "- DOCUMENTATION: $DOCUMENTATION" >> $GITHUB_STEP_SUMMARY
        env:
          API: ${{ steps.dist-exists.outputs.api }}
          CLIENT: ${{ steps.dist-exists.outputs.client }}
          ELEMENTS: ${{ steps.dist-exists.outputs.elements }}
          DOCUMENTATION: ${{ steps.dist-exists.outputs.documentation }}

  deploy-api:
    needs: checks
    if: ${{ (inputs.api == true || inputs.api == 'true') && needs.checks.outputs.api == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          firebase-tools: true

      - name: Download dist artifact
        uses: ./.github/actions/dist-artifact-download

      # This job works only with a paid plan such as Blaze (https://firebase.google.com/pricing/)
      # - name: Deploy api
      #   if: ${{ (fromJSON(needs.checks.outputs.changes).dependencies == 'true' || fromJSON(needs.checks.outputs.changes).src == 'true') && needs.checks.outputs.origin == 'true' }}
      #   run: |
      #     npx nx build api --configuration firebase
      #     yarn firebase:deploy:ci:api || exit 1
      #   env:
      #     FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

  deploy-client:
    needs: checks
    if: ${{ (inputs.client == true || inputs.client == 'true') && needs.checks.outputs.client == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          firebase-tools: true

      - name: Download dist artifact
        uses: ./.github/actions/dist-artifact-download

      - name: Deploy client
        run: yarn firebase:deploy:ci:client || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

  deploy-elements:
    needs: checks
    if: ${{ (inputs.elements == true || inputs.elements == 'true') && needs.checks.outputs.elements == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          firebase-tools: true

      - name: Download dist artifact
        uses: ./.github/actions/dist-artifact-download

      - name: Deploy elements
        run: |
          bash tools/shell/generate-elements-bootstrap-script.sh ./dist/apps elements
          yarn firebase:deploy:ci:elements || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}

  deploy-documentation:
    needs: checks
    if: ${{ (inputs.documentation == true || inputs.documentation == 'true') && needs.checks.outputs.documentation == 'true' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          firebase-tools: true

      - name: Download dist artifact
        uses: ./.github/actions/dist-artifact-download

      - name: Deploy documentation
        run: yarn firebase:deploy:ci:documentation || exit 1
        env:
          FIREBASE_DEPLOY_TOKEN: ${{ secrets.FIREBASE_DEPLOY_TOKEN }}
