# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: test-e2e

on:
  workflow_dispatch:

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.ref_name }}.${{ github.sha }}.test-e2e
  cancel-in-progress: true

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Setup environment
        uses: ./.github/actions/setup-environment
        with:
          cypress: true

      - name: E2E all
        run: |
          npx nx run-many --target configure-env --all
          npx nx run-many --target e2e --all
          npx nx run-many --target configure-env --all --reset
